import { ProjectsSectionType } from '@/lib/types/sections'
import { getId } from '@/lib/utils/helper';
import Image from 'next/image';

export const projectsSection: ProjectsSectionType = {
    title: 'All Members',
    projects: [
    {
        id: getId(),
        name: 'Jaee Madhyeshwar',
        post: 'Executive Vice President',
        url: '',
        img: '/EVP.jpg',
        year: 22, 
        tags: [],
    },    
    {
        id: getId(),
        name: 'Yash Khatri',
        post: 'President',
        url: '',
        img: '/P.jpg',
        year: 24, 
        tags: [],
    },        
    {
        id: getId(),
        name: 'Pratik Take',
        post: 'Vice President',
        url: '',
        img: '/VP.jpg',
        year: 23, 
        tags: [],
    },
    {
        id: getId(),
        name: 'Bhushan Chilange',
        post: 'Event Head',
        url: '',
        img: '/EH1.jpg',
        year: 11, 
        tags: [],
    },
    {
        id: getId(),
        name: 'Avantika Katewar',
        post: 'Publicity Head',
        url: '',
        img: '/PH1.jpg',
        year: 10, 
        tags: [],
    },
    {
        id: getId(),
        name: 'Manish Choudhari',
        post: 'Disciplinary Head',
        url: '',
        img: '/DH1.jpg',
        year: 0, 
        tags: [],
    },
    {
        id: getId(),
        name: 'Vaishwik Dumpalwar',
        post: 'Event Head',
        url: '',
        img: '/EH2.jpg',
        year: 9, 
        tags: [],
    },
    {
        id: getId(),
        name: 'Mayuri Kanire',
        post: 'Disciplinary Head',
        url: '',
        img: '/DH2.jpg',
        year: -1, 
        tags: [],
    },
    {
        id: getId(),
        name: 'Ayush Datir',
        post: 'Disciplinary Head',
        url: '',
        img: '/DH3.jpg',
        year: 2, 
        tags: [],
    },
    {
        id: getId(),
        name: 'Daivik Arigela',
        post: 'Event Manager',
        url: '',
        img: '/EM1.jpg',
        year: 13, 
        tags: [],
    },
    {
        id: getId(),
        name: 'Janhavi Landge',
        post: 'Event Manager',
        url: '',
        img: '/EM2.jpg',
        year: 14, 
        tags: [],
    },
    {
        id: getId(),
        name: 'Ishika Chauhan',
        post: 'Disciplinary head',
        url: '',
        img: '/DH4.jpg',
        year: 1, 
        tags: [],
    },
    {
        id: getId(),
        name: 'Narayani Fopse',
        post: 'Decoration Head',
        url: '',
        img: '/DCH1.jpg',
        year: 8, 
        tags: [],
    },
    {
        id: getId(),
        name: 'Shruti Dhote',
        post: 'Decoration Head',
        url: '',
        img: '/DCH2.jpg',
        year: 7, 
        tags: [],
    },
    {
        id: getId(),
        name: 'Vedanti Bele',
        post: 'Publicity Head',
        url: '',
        img: '/PH2.jpg',
        year: 4, 
        tags: [],
    },
    {
        id: getId(),
        name: 'Sangram Puri',
        post: 'Sports Head',
        url: '',
        img: '/SH1.jpg',
        year: 6, 
        tags: [],
    },
    {
        id: getId(),
        name: 'Prachi Singhare',
        post: 'Magazine Head',
        url: '',
        img: '/MH1.jpg',
        year: 15, 
        tags: [],
    },
    {
        id: getId(),
        name: 'Sanika Zodape',
        post: 'Secretary',
        url: '',
        img: '/S.jpg',
        year: 21, 
        tags: [],
    },
    {
        id: getId(),
        name: 'Shahnawaj Mirza',
        post: 'Treasurer',
        url: '',
        img: '/T.jpg',
        year: 18, 
        tags: [],
    },
    {
        id: getId(),
        name: 'Ravina Billore',
        post: 'Event Head',
        url: '',
        img: '/EH3.jpg',
        year: 3, 
        tags: [],
    },
    {
        id: getId(),
        name: 'Aditya Singh',
        post: 'Website Head',
        url: '',
        img: '/Aditya Singh.jpg',
        year: 17, 
        tags: [],
    },
    {
        id: getId(),
        name: 'Vedant Ekale',
        post: 'Website Head',
        url: '',
        img: '/WH1.jpg',
        year: 16, 
        tags: [],
    },
    {
        id: getId(),
        name: 'Sakshi Nikhade',
        post: 'Sports Head',
        url: '',
        img: '/SH2.jpg',
        year: 5, 
        tags: [],
    },
    {
        id: getId(),
        name: 'Sudhanshu kodke',
        post: 'Joint Secretary',
        url: '',
        img: '/JS.jpg',
        year: 20, 
        tags: [],
    },
    {
        id: getId(),
        name: 'Vinayak Chaudhari',
        post: 'Event Head',
        url: '',
        img: '/EH4.jpg',
        year: 12, 
        tags: [],
    },
    {
        id: getId(),
        name: 'Sanskruti Kumar',
        post: 'Joint Treasurer',
        url: '',
        img: '/JT.jpg',
        year: 19, 
        tags: [],
    },
    ],
};
